// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mawuanluxfvlbzkhnplv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hd3Vhbmx1eGZ2bGJ6a2hucGx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzc3NTAsImV4cCI6MjA3Mzc1Mzc1MH0.71PL9AbvSMmVhFN6QJiTgUAT1yMNZiabb8w_W_gA4F0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});